{% set name = "justpy" %}
{% set version = "0.12.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/justpy-{{ version }}.tar.gz
  sha256: 285fa923c1a3020fb4a728415976489627efb6c0665294e650855f1947e9729a


build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - hatchling
    - pip
    - python >=3.7
  run:
    - addict >=2.4.0
    - aiofiles
    - hjson-py >=3.1.0
    - httpx >=0.23.0
    - itsdangerous >=2.1.2
    - jinja2 >=3.1.2
    - python >=3.7
    - starlette >=0.20.4
    - twine
    - uvicorn >=0.18.3
    - websockets
    - wheel

test:
  imports:
    - justpy
  commands:
    - pip check
  requires:
    - pip
    - aiohttp
    - asynctest
    - green
    - psutil
    - selenium
    - testfixtures
    - webdriver-manager

about:
  home: https://justpy.io
  summary: JustPy is an object-oriented, component based, high-level Python Web Framework that requires no front-end programming
  license: Apache-2.0
  license_file: LICENSE
  dev_url: https://github.com/justpy-org/justpy

extra:
  recipe-maintainers:
    - marcobonifacio
