{% set name = "justpy" %}
{% set version = "0.5.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/justpy-{{ version }}.tar.gz
  sha256: 822d36528a0203e07594e7fcd64b51e5057f90fccd4e987e35a2c083fe6bc0a2


build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - flit >=3.2,<4
    - pip
    - python >=3.7
  run:
    - addict >=2.4.0
    - aiofiles
    - demjson3 >=3.0.5
    - httpx >=0.23.0
    - itsdangerous >=2.1.2
    - jinja2 >=3.1.2
    - python >=3.7
    - starlette >=0.20.4
    - twine
    - uvicorn >=0.18.3
    - websockets
    - wheel

test:
  imports:
    - justpy
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://justpy.io
  summary: JustPy is an object-oriented, component based, high-level Python Web Framework that requires no front-end programming
  license: Apache-2.0
  license_file: LICENSE
  dev_url: https://github.com/justpy-org/justpy

extra:
  recipe-maintainers:
    - marcobonifacio
