{% set name = "justpy" %}
{% set version = "0.2.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/justpy-{{ version }}.tar.gz
  sha256: 682246de9db9febbf0ad9306ef0e9efc20d512744f225afcbec3f584233b66a8

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - flit
    - pip
    - python >=3.6
  run:
    - addict >=2.2.1
    - aiofiles
    - demjson3
    - httpx >=0.11.0
    - itsdangerous >=1.1.0
    - jinja2 >=2.10.1
    - python >=3.6
    - starlette >=0.12.0
    - twine
    - uvicorn >=0.7.1
    - websockets
    - wheel

test:
  imports:
    - justpy
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://justpy.io
  summary: JustPy is an object-oriented, component based, high-level Python Web Framework that requires no front-end programming
  license: Apache-2.0
  license_file: LICENSE
  dev_url: https://github.com/elimintz/justpy

extra:
  recipe-maintainers:
    - marcobonifacio
