{% set name = "justpy" %}
{% set version = "0.5.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/justpy-{{ version }}.tar.gz
  sha256: 38ff297648f40a067881246e39089eca7290f47dceee95916d66bdf662248ae2


build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - flit
    - pip
    - python >=3.6
  run:
    - addict >=2.4.0
    - aiofiles
    - demjson3 >=3.0.5
    - httpx >=0.23.0
    - itsdangerous >=2.1.2
    - jinja2 >=3.1.2
    - python >=3.6
    - starlette >=0.20.4
    - twine
    - uvicorn >=0.18.3
    - websockets
    - wheel

test:
  imports:
    - justpy
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://justpy.io
  summary: JustPy is an object-oriented, component based, high-level Python Web Framework that requires no front-end programming
  license: Apache-2.0
  license_file: LICENSE
  dev_url: https://github.com/elimintz/justpy

extra:
  recipe-maintainers:
    - marcobonifacio
